### ISSUE TITLE
Feature: Click function to search around clicked area

### ISSUE THREAD

**Issue by macdhollister** [macdhollister/project1#9]
I noticed that really populated areas (i.e. Downtown), show a very dense cluster of shops, and then nothing for the rest of the neighborhood. This seems like pretty poor design, especially considering it means shops in other areas of the neighborhoods will never appear on our site.

As a fix to this, we could add a function that searches around a specified point that they click, straight from the map. Thoughts?

**Comment by JonathanDavis22** [comment]
That's a real concern and a great idea to try and circumvent this issue with a new feature. We should try to crack this in class today.
